# Generated by Django 5.2.5 on 2026-03-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('post_nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=100, unique=True)),
                ('fonction', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cartes/')),
            ],
        ),
    ]
