# Generated by Django 5.2.5 on 2026-03-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='grade',
            field=models.CharField(choices=[('Lt Col', 'Lt Col'), ('Col', 'Col'), ('Lt', 'Lt'), ('SLt', 'SLt'), ('SOFFR', 'SOFFR'), ('1Cl', '1Cl'), ('2Cl', '2Cl'), ('Cpl', 'Cpl'), ('AdjChef', 'AdjChef'), ('SrgMaj', 'SrgMaj'), ('Cap', 'Cap'), ('Maj', 'Maj')], max_length=20),
        ),
    ]
