# Generated by Django 5.2.5 on 2026-03-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_carte_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='numero',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
