# Generated by Django 5.2.5 on 2026-03-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_carte_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='carte',
            name='profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils/'),
        ),
    ]
